### PR TITLE
run travis tests with Go 1.9

### PR DESCRIPTION
**Pull request by adamdecaf**
I think this is why #5 and #6 are failing.

### CODE REVIEW

**Comment by shift** [comment]
As some people use older versions with pre-packaged older golang (eg. embedded distros), I'd prefer to use a test matrix for this.

**Comment by adamdecaf** [comment]
Go 1.7 needs to be required for this though? It looks like there's a problem with zonedb. 
https://travis-ci.org/shift/domain_exporter/jobs/341661952#L458

I see you added the test matrix over in: https://github.com/shift/domain_exporter/commit/a1393c7cb2ade5491f078ed0d7d008dc377edb1b

**Comment by adamdecaf** [comment]
I think zonedb is only being built on Go 1.9.x.

Their CI file doesn't specify anything but the docker image: https://github.com/zonedb/zonedb/blob/master/.circleci/config.yml

domainr/ci Specifies Go 1.9.4: https://github.com/domainr/ci/blob/master/Dockerfile#L3

The tag was updated 44 mins ago (as of writing): https://hub.docker.com/r/domainr/ci/tags/

**Comment by shift** [comment]
Messaged you on freenode btw.

I'll be allowing failures on CI for tip and 1.7.x in the next merge.

**Comment by adamdecaf** [comment]
Sounds good. I'm going to close this PR then. Thanks!

**Pull request closed without merging**
