### PR TITLE
Support tracking which domains fail to parse

### PR DESCRIPTION
**Pull request by Vaelatern**
In reference to #21

### CODE REVIEW

**Comment by Vaelatern** [comment]
I am not sure of my use of Gauge, but... it seems the best fitting of the 4.

**Comment by adamdecaf** [comment]
I think this would work for the example alerts (I added an alert for this).

```yaml
groups:
 - name: ./domain.rules
   rules:
    - alert: DomainExpiring
      expr: domain_expiration{} < 45
      for: 24h
      labels:
        severity: warning
      annotations:
        description: "{{ $labels.domain }} expires in {{ $value }} days"
    - alert: DomainUnfindable
      expr: domain_expiration_unfindable > 0
      for: 24h
      labels:
        severity: critical
      annotations:
        description: "Unable to find or parse expiry for {{ $labels.domain }}"
```

**Comment by adamdecaf** [comment]
@Vaelatern We could do a counter to also measure how many times a domain fails to parse/whois response.

**Comment by Vaelatern** [comment]
Counters don't get labels either.

**Comment by adamdecaf** [comment]
I've been able to add labels on a counter. 

- https://github.com/prometheus/client_golang/blob/master/prometheus/counter.go#L203
- https://github.com/moov-io/auth/blob/6d276c125f86e100e73a2a5fdff803feee458ad6/main.go#L37

**Comment by Vaelatern** [comment]
The #prometheus room on freenode suggested
`<SuperQ> Vaelatern: Yes, a simple gauge with a value of 1 is used for "info" metrics`

**Comment by Vaelatern** [comment]
Really, it's whether a metric failed that matters, not that it increases. The timing of the increase would matter too... has it not increased in a day? A week? Or just 2 hours? In this, I think a gauge serves the user best.

**Comment by adamdecaf** [comment]
A Gauge works for me.

**Pull request merged**
